version: "3.8"
services:
  Image-Upload-Application:
    image: postgres:latest
    container_name: ImageUpload-Container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
